### ISSUE TITLE
There is no get.js

### ISSUE THREAD

**Issue by silencej** [lsabbagh/faxios#2]
https://github.com/lsabbagh/faxios/blob/db78420f53795be22347ac355053b4af91c14191/lib/fetch.js#L9

**Comment by lsabbagh** [comment]
@silencej thanks for the notice, I will fix it nearly and start adding the test units...

**Comment by lsabbagh** [comment]
@silencej fixed

**Comment by silencej** [comment]
@lsabbagh Thank you for your work! :+1:
